// web/src/pages/LoginPage.tsx
import { motion } from 'framer-motion';
import { Button } from '@/components/ui/button';
import { Zap, Sparkles, Shield, GitBranch } from 'lucide-react';

const features = [
  {
    icon: Sparkles,
    title: 'AI-Powered',
    description: 'Claude handles your tasks autonomously',
  },
  {
    icon: Shield,
    title: 'Private & Secure',
    description: 'Your data stays in your isolated environment',
  },
  {
    icon: GitBranch,
    title: 'Git Integration',
    description: 'Automatic branches and pull requests',
  },
];

export function LoginPage() {
  return (
    <div className="min-h-screen flex">
      {/* Left side - Branding */}
      <div className="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-primary/10 via-purple-500/5 to-background p-12 flex-col justify-between">
        <div>
          <motion.div
            initial={{ opacity: 0, y: -20 }}
            animate={{ opacity: 1, y: 0 }}
            className="flex items-center gap-3"
          >
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center">
              <Zap className="h-6 w-6 text-white" />
            </div>
            <span className="font-bold text-2xl">
              task<span className="text-primary">you</span>
            </span>
          </motion.div>

          <motion.div
            initial={{ opacity: 0, y: 20 }}
            animate={{ opacity: 1, y: 0 }}
            transition={{ delay: 0.2 }}
            className="mt-16"
          >
            <h1 className="text-4xl font-bold leading-tight mb-4">
              Your AI-powered
              <br />
              task execution engine
            </h1>
            <p className="text-lg text-muted-foreground max-w-md">
              Delegate coding tasks to Claude and watch them get done.
              Review PRs, not implementations.
            </p>
          </motion.div>

          <motion.div
            initial={{ opacity: 0 }}
            animate={{ opacity: 1 }}
            transition={{ delay: 0.4 }}
            className="mt-12 space-y-6"
          >
            {features.map((feature, i) => (
              <motion.div
                key={feature.title}
                initial={{ opacity: 0, x: -20 }}
                animate={{ opacity: 1, x: 0 }}
                transition={{ delay: 0.5 + i * 0.1 }}
                className="flex items-start gap-4"
              >
                <div className="p-2 rounded-lg bg-primary/10 shrink-0">
                  <feature.icon className="h-5 w-5 text-primary" />
                </div>
                <div>
                  <h3 className="font-medium">{feature.title}</h3>
                  <p className="text-sm text-muted-foreground">{feature.description}</p>
                </div>
              </motion.div>
            ))}
          </motion.div>
        </div>

        <motion.p
          initial={{ opacity: 0 }}
          animate={{ opacity: 1 }}
          transition={{ delay: 0.8 }}
          className="text-sm text-muted-foreground"
        >
          Powered by Anthropic's Claude
        </motion.p>
      </div>

      {/* Right side - Login */}
      <div className="flex-1 flex items-center justify-center p-8">
        <motion.div
          initial={{ opacity: 0, scale: 0.95 }}
          animate={{ opacity: 1, scale: 1 }}
          className="w-full max-w-sm"
        >
          {/* Mobile logo */}
          <div className="lg:hidden flex items-center justify-center gap-3 mb-8">
            <div className="h-10 w-10 rounded-xl bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center">
              <Zap className="h-6 w-6 text-white" />
            </div>
            <span className="font-bold text-2xl">
              task<span className="text-primary">you</span>
            </span>
          </div>

          <div className="text-center mb-8">
            <h2 className="text-2xl font-bold mb-2">Welcome</h2>
            <p className="text-muted-foreground">
              Sign in to start executing tasks
            </p>
          </div>

          <div className="space-y-3">
            <Button
              className="w-full h-12 text-base"
              variant="outline"
              onClick={() => window.location.href = '/api/auth/google'}
            >
              <svg className="mr-3 h-5 w-5" viewBox="0 0 24 24">
                <path
                  fill="#4285F4"
                  d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z"
                />
                <path
                  fill="#34A853"
                  d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z"
                />
                <path
                  fill="#FBBC05"
                  d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z"
                />
                <path
                  fill="#EA4335"
                  d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z"
                />
              </svg>
              Continue with Google
            </Button>

            <Button
              className="w-full h-12 text-base"
              variant="outline"
              onClick={() => window.location.href = '/api/auth/github'}
            >
              <svg className="mr-3 h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
                <path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
              </svg>
              Continue with GitHub
            </Button>
          </div>

          <p className="text-xs text-center text-muted-foreground mt-8">
            By signing in, you agree to our{' '}
            <a href="#" className="underline hover:text-foreground">Terms of Service</a>
            {' '}and{' '}
            <a href="#" className="underline hover:text-foreground">Privacy Policy</a>
          </p>
        </motion.div>
      </div>
    </div>
  );
}

// pilot/src/lib/components/LoginPage.svelte
<script lang="ts">
	import { Zap, Sparkles, Shield, GitBranch } from 'lucide-svelte';

	const features = [
		{ icon: Sparkles, title: 'AI-Powered', description: 'Claude handles your tasks autonomously' },
		{ icon: Shield, title: 'Private & Secure', description: 'Your data stays in your isolated project environment' },
		{ icon: GitBranch, title: 'Git Integration', description: 'Automatic branches and pull requests' },
	];
</script>

<div class="min-h-screen flex">
	<!-- Left side - Branding -->
	<div class="hidden lg:flex lg:w-1/2 bg-gradient-to-br from-primary/10 via-purple-500/5 to-background p-12 flex-col justify-between">
		<div>
			<div class="flex items-center gap-3">
				<div class="h-10 w-10 rounded-xl bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center">
					<Zap class="h-6 w-6 text-white" />
				</div>
				<span class="font-bold text-2xl">
					task<span class="text-primary">you</span>
				</span>
			</div>

			<div class="mt-16">
				<h1 class="text-4xl font-bold leading-tight mb-4">
					Your AI-powered<br />task execution engine
				</h1>
				<p class="text-lg text-muted-foreground max-w-md">
					Delegate coding tasks to Claude and watch them get done.
					Review PRs, not implementations.
				</p>
			</div>

			<div class="mt-12 space-y-6">
				{#each features as feature}
					<div class="flex items-start gap-4">
						<div class="p-2 rounded-lg bg-primary/10 shrink-0">
							<feature.icon class="h-5 w-5 text-primary" />
						</div>
						<div>
							<h3 class="font-medium">{feature.title}</h3>
							<p class="text-sm text-muted-foreground">{feature.description}</p>
						</div>
					</div>
				{/each}
			</div>
		</div>

		<p class="text-sm text-muted-foreground">
			Powered by Anthropic's Claude &bull; Running on Cloudflare
		</p>
	</div>

	<!-- Right side - Login -->
	<div class="flex-1 flex items-center justify-center p-8">
		<div class="w-full max-w-sm">
			<!-- Mobile logo -->
			<div class="lg:hidden flex items-center justify-center gap-3 mb-8">
				<div class="h-10 w-10 rounded-xl bg-gradient-to-br from-primary to-purple-600 flex items-center justify-center">
					<Zap class="h-6 w-6 text-white" />
				</div>
				<span class="font-bold text-2xl">
					task<span class="text-primary">you</span>
				</span>
			</div>

			<div class="text-center mb-8">
				<h2 class="text-2xl font-bold mb-2">Welcome</h2>
				<p class="text-muted-foreground">
					Sign in to start executing tasks
				</p>
			</div>

			<div class="space-y-3">
				<a
					href="/api/auth/google"
					class="w-full h-12 text-base flex items-center justify-center gap-3 rounded-lg border border-input bg-background px-4 font-medium hover:bg-accent hover:text-accent-foreground transition-colors"
				>
					<svg class="h-5 w-5" viewBox="0 0 24 24">
						<path fill="#4285F4" d="M22.56 12.25c0-.78-.07-1.53-.2-2.25H12v4.26h5.92c-.26 1.37-1.04 2.53-2.21 3.31v2.77h3.57c2.08-1.92 3.28-4.74 3.28-8.09z" />
						<path fill="#34A853" d="M12 23c2.97 0 5.46-.98 7.28-2.66l-3.57-2.77c-.98.66-2.23 1.06-3.71 1.06-2.86 0-5.29-1.93-6.16-4.53H2.18v2.84C3.99 20.53 7.7 23 12 23z" />
						<path fill="#FBBC05" d="M5.84 14.09c-.22-.66-.35-1.36-.35-2.09s.13-1.43.35-2.09V7.07H2.18C1.43 8.55 1 10.22 1 12s.43 3.45 1.18 4.93l2.85-2.22.81-.62z" />
						<path fill="#EA4335" d="M12 5.38c1.62 0 3.06.56 4.21 1.64l3.15-3.15C17.45 2.09 14.97 1 12 1 7.7 1 3.99 3.47 2.18 7.07l3.66 2.84c.87-2.6 3.3-4.53 6.16-4.53z" />
					</svg>
					Continue with Google
				</a>

				<a
					href="/api/auth/github"
					class="w-full h-12 text-base flex items-center justify-center gap-3 rounded-lg border border-input bg-background px-4 font-medium hover:bg-accent hover:text-accent-foreground transition-colors"
				>
					<svg class="h-5 w-5" viewBox="0 0 24 24" fill="currentColor">
						<path d="M12 0c-6.626 0-12 5.373-12 12 0 5.302 3.438 9.8 8.207 11.387.599.111.793-.261.793-.577v-2.234c-3.338.726-4.033-1.416-4.033-1.416-.546-1.387-1.333-1.756-1.333-1.756-1.089-.745.083-.729.083-.729 1.205.084 1.839 1.237 1.839 1.237 1.07 1.834 2.807 1.304 3.492.997.107-.775.418-1.305.762-1.604-2.665-.305-5.467-1.334-5.467-5.931 0-1.311.469-2.381 1.236-3.221-.124-.303-.535-1.524.117-3.176 0 0 1.008-.322 3.301 1.23.957-.266 1.983-.399 3.003-.404 1.02.005 2.047.138 3.006.404 2.291-1.552 3.297-1.23 3.297-1.23.653 1.653.242 2.874.118 3.176.77.84 1.235 1.911 1.235 3.221 0 4.609-2.807 5.624-5.479 5.921.43.372.823 1.102.823 2.222v3.293c0 .319.192.694.801.576 4.765-1.589 8.199-6.086 8.199-11.386 0-6.627-5.373-12-12-12z" />
					</svg>
					Continue with GitHub
				</a>
			</div>

			<p class="text-xs text-center text-muted-foreground mt-8">
				By signing in, you agree to our
				<a href="#terms" class="underline hover:text-foreground">Terms of Service</a>
				and
				<a href="#privacy" class="underline hover:text-foreground">Privacy Policy</a>
			</p>
		</div>
	</div>
</div>
